apiVersion: v1
kind: Service
metadata:
  name: zaap-runner
  namespace: zaap
spec:
  type: NodePort
  selector:
    app: zaap-runner
  ports:
    - name: grpc
      port: 80
      targetPort: grpc
      protocol: TCP
