version: '3'
services:
  registry:
    image: registry
    environment:
      - "REGISTRY_NOTIFICATIONS_ENDPOINTS=- name: zaap-hook\n  url: ${REGISTRY_AUTH_SERVER:-http://host.docker.internal:8091/hook}\n  timeout: 10s\n  threshold: 8\n  backoff: 10s"
    ports:
      - 5000:5000
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: zaap
      POSTGRES_USER: zaap
      POSTGRES_PASSWORD: zaap
    volumes:
      - postgres:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
volumes:
  postgres: {}
  rabbitmq: {}
