version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd
    ports:
      - 2379:2379
      - 2380:2380
  proxy:
    image: envoyproxy/envoy:latest
    volumes:
      - ./envoy:/etc/envoy
      - ./protocol:/protocol
    ports:
      - 9000:9000
      - 9001:9001
volumes:
  postgres: {}
