name: Service apiserver
on: [push]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and deploy
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v1
        with:
          username: remicaumette
          password: ${{ secrets.REMICAUMETTE_GH_TOKEN }}
          registry: docker.pkg.github.com
          repository: expectedsh/zaap.sh/apiserver
          dockerfile: zaap-services/cmd/zaap-apiserver/Dockerfile
          tags: latest

      - name: Tagging
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo $DOCKER_PASSWORD | docker login docker.pkg.github.com -u $DOCKER_USERNAME --password-stdin
          docker pull $IMAGE:latest
          docker tag $IMAGE:latest $IMAGE:$(echo $GITHUB_REF | cut -c 11-)
          docker push $IMAGE:$(echo $GITHUB_REF | cut -c 11-)
        env:
          DOCKER_USERNAME: remicaumette
          DOCKER_PASSWORD: ${{ secrets.REMICAUMETTE_GH_TOKEN }}
          IMAGE: docker.pkg.github.com/expectedsh/zaap.sh/apiserver
